#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyPay.Resource", IsApplication=true)]

namespace MyPay
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_overflow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_pie_chart = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ProgressBarStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int TextboxStyle = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int HeaderTextView2 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int HeaderTextView3 = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int cbIsMetro = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int editAmount = 2131165209;
			
			// aapt resource value: 0x7f070007
			public const int editBasic = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int editCtc = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int editShiftAllowance = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int lbl1 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int lbl2 = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int lbl3 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int lbl4 = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int lbl5 = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int listMyInfo = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int listSharedBy = 2131165193;
			
			// aapt resource value: 0x7f07001a
			public const int menu = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int sample_main_layout = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int sliding_tabs = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int txtDescription = 2131165208;
			
			// aapt resource value: 0x7f070001
			public const int view2 = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int view3 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int viewCtc = 2131165197;
			
			// aapt resource value: 0x7f070017
			public const int viewPager = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int viewPaycheck = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int viewPf = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int viewTaxableIncome = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int viewTotalTax = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int viewVariable = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Frag1Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Frag2Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Frag3Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Frag4Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PropertyListItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
